name: test-build

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - release/*
      - support/*
      - hotfix/*
    paths:
     - src/**
     - build/**
  workflow_dispatch:
  
jobs:
  actions-test:
    name: actions test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: set variables
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_SHA=$shortSha" >> $GITHUB_ENV
    
      - name: print variables
        run: |
          echo "Repository name: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Branch Name: $GITHUB_REF_NAME"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run Number: $GITHUB_RUN_NUMBER"
          echo "SHA: $GITHUB_WORKFLOW_SHA"
          echo "Short SHA: $SHORT_SHA"
