name: test-build

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - release/*
      - support/*
      - hotfix/*
    paths:
     - src/**
     - build/**
  workflow_dispatch:
  
jobs:
  actions-test:
    name: actions test
    runs-on: ubuntu-latest
    steps:
      - name: set variables
        run: |
          echo "Repository name: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Branch Name: $GITHUB_REF_NAME"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "SHA: $GITHUB_WORKFLOW_SHA"
